### ISSUE TITLE
Remove dependency on elm-test

### ISSUE THREAD

**Issue by MazeChaZer** [knledg/touch-events#15]
Installing touch-events pulls in elm-test and its dependencies. There should probably be a separate `elm-package.json` for the test files, which includes elm-test as a dependency. This is explained in detail [here](https://medium.com/@_rchaves_/testing-in-elm-93ad05ee1832#.dxkm4imuc), section “Tree structure“

**Comment by martinlechner1** [comment]
Can you please publish the current master to elm package repo to finally remove the elm-package dependency.

**Comment by andys8** [comment]
@mattludwigs Would be great :+1:

**Comment by mattludwigs** [comment]
@martinlechner1 and @andys8 I will do that today, thank you for reminding me!

**Comment by mattludwigs** [comment]
Done: http://package.elm-lang.org/packages/knledg/touch-events/latest

`v 2.1.2`
